
#BANCOS


### GET /api/banks
GET http://localhost:3000/api/banks

### GET /api/banks/bypage/:npage
GET http://localhost:3000/api/banks/bypage/1

### GET /api/banks/:id
GET http://localhost:3000/api/banks/2

### DELETE /api/banks/:id
DELETE http://localhost:3000/api/banks/5

### POST /api/banks
POST http://localhost:3000/api/banks
Content-Type: application/json

{
  "name": "Banco Central",
  "n_employees": 120,
  "initial_cap": 5000000,
  "foundation": "1998-05-12",
  "active": true
}

### PUT /api/banks/:id
PUT http://localhost:3000/api/banks/2
Content-Type: application/json

{
  "name": "Banco Central Renovado",
  "n_employees": 150,
  "initial_cap": 7500000,
  "foundation": "1998-05-12",
  "active": false
}

### GET /api/banks/filter
GET http://localhost:3000/api/banks/filter?name=ban&initial_cap=5000000=&active=true




