#SUCURSALES


### GET /api/branches
GET http://localhost:3000/api/branches

### GET /api/branches/:id
GET http://localhost:3000/api/branches/1

### DELETE /api/branches/:id
DELETE http://localhost:3000/api/branches/5

### POST /api/branches
POST http://localhost:3000/api/branches
Content-Type: application/json

{
  "name": "Sucursal Sevilla Centro",
  "n_tellers": 25,
  "monthly_income": 200000,
  "opening_date": "2010-03-15",
  "open": true,
  "id_bank": 1
}

### PUT /api/branches/:id
PUT http://localhost:3000/api/branches/21
Content-Type: application/json

{
  "name": "Sucursal Sevilla Centro Renovada",
  "n_tellers": 25,
  "monthly_income": 200000,
  "opening_date": "2010-03-15",
  "open": true,
  "id_bank": 1
}

### GET /api/branches/filter
GET http://localhost:3000/api/branches/filter?name=Sucursal&dateMin=2000-01-15&dateMax=&id_bank=2
