### GET /api/banks recupera todos los bancos
GET http://localhost:3000/api/banks


### GET /api/banks/id recupera todos los bancos por ID
GET http://localhost:3000/api/banks/1

### DELETE /api/banks/id borra un banco por ID
DELETE http://localhost:3000/api/banks/5


### POST /api/banks crea un nuevo banco
POST http://localhost:3000/api/banks
Content-Type: application/json

{
  "name": "Banco Central",
  "n_employees": 120,
  "initial_cap": 5000000,
  "foundation": "1998-05-12",
  "active": true
}

### PUT /api/banks/id actualiza un banco existente
PUT http://localhost:3000/api/banks/4
Content-Type: application/json

{
  "name": "Banco Central Renovado",
  "n_employees": 150,
  "initial_cap": 7500000,
  "foundation": "1998-05-12",
  "active": false
}
